### ISSUE TITLE
testissue

### ISSUE THREAD

**Issue by mijnmodelbaan** [mijnmodelbaan/justforsaving#1]
![20190918_121854](https://user-images.githubusercontent.com/31405979/66110590-6529c680-e5c7-11e9-9a74-aba86d0bd7b4.jpg)

![20190918_122039](https://user-images.githubusercontent.com/31405979/66110678-8f7b8400-e5c7-11e9-9695-5e017713622e.jpg)

![20190918_122129](https://user-images.githubusercontent.com/31405979/66110733-a621db00-e5c7-11e9-9076-51f1623b90a7.jpg)

![20190918_121926](https://user-images.githubusercontent.com/31405979/66110791-c94c8a80-e5c7-11e9-896c-1505e7ec5917.png)

![20190918_122059](https://user-images.githubusercontent.com/31405979/66112156-9d7ed400-e5ca-11e9-8137-892644c0e513.jpg)

![20190918_122058](https://user-images.githubusercontent.com/31405979/66112354-f6e70300-e5ca-11e9-9378-095c42e2bfbc.jpg)

**Comment by mijnmodelbaan** [comment]
This issue will be closed. Sorted.

**Comment by morettty** [comment]
Could you flash cutting this track?
i am not capable of tasmot flash.
can you tell me how did you get it

Thank you

**Comment by mijnmodelbaan** [comment]
Hi Moretty,

After cutting the track to RXD0 and connecting GPIO0 to GND, I was able to flash the TYWE3S module w/o any problem.
Make sure you disconnect the module from the MAINS power and use the 3.3 Volt from your flashing device.
Worked like a charm for me.

BR//Willem.

**Comment by morettty** [comment]
> Hi Moretty,
> 
> After cutting the track to RXD0 and connecting GPIO0 to GND, I was able to flash the TYWE3S module w/o any problem.
> Make sure you disconnect the module from the MAINS power and use the 3.3 Volt from your flashing device.
> Worked like a charm for me.
> 
> BR//Willem.

Thank you very much. It worked perfect. Can you tell me how you have it configured with tasmota? The LEDs and the middle button do not like how they are

**Comment by morettty** [comment]
I am using template {"NAME": "Yours Shutter", "GPIO": [157,0,54,10,22,19,0,0,17,21,53,23,52], "FLAG": 0, "BASE": 18} but I am not able to get the buttons right.
can you tell me how to configure shutter suport and all the configuration.
Thank you

**Comment by mijnmodelbaan** [comment]
Hi Moretty,

I'm using (and contributed) the template [https://templates.blakadder.com/WF-CS01_EU.html](https://templates.blakadder.com/WF-CS01_EU.html).

This is working very well for my shutters. You could try using [https://templates.blakadder.com/etersky_WF-CS01.html](https://templates.blakadder.com/etersky_WF-CS01.html) or [https://templates.blakadder.com/WF-CS02_EU.html](https://templates.blakadder.com/WF-CS02_EU.html).

Did you enable shutter support in Tasmota? I didn't because it wasn't there at the time I configured my shutters.

Hope you get it working.

BR//Willem.

**Comment by morettty** [comment]
> Hola Moretty,
> 
> Estoy usando (y contribuí) la plantilla https://templates.blakadder.com/WF-CS01_EU.html .
> 
> Esto funciona muy bien para mis contraventanas. Puede intentar usar https://templates.blakadder.com/etersky_WF-CS01.html o https://templates.blakadder.com/WF-CS02_EU.html .
> 
> ¿Habilitó el soporte del obturador en Tasmota? No lo hice porque no estaba allí en el momento en que configuré mis persianas.
> 
> Espero que lo hagas funcionar.
> 
> BR // Willem.

Thank you very much for the help. It worked perfect for me, but now I have another problem. I bought two more and they changed the plate, do you know or does someone know how the new 3V1 flash 2019-12-22.
